# LLM ocenjivanje relevantnosti query–product parova

Za svaki par koji čine korisnički upit i jedan proizvod, model dobija:
- tekst upita
- naziv, brend i kategoriju proizvoda
- opis proizvoda
- pros, cons i best_uses

Model svakom paru dodeljuje ocenu relevantnosti 0 - 3 i kratko obrazloženje ocene.

## 1. Učitavanje biblioteka

In [ ]:
import random
import numpy as np
from huggingface_hub import model_info
from transformers import AutoModelForCausalLM, AutoTokenizer
from pathlib import Path
import torch
import sys
import json
import re
import pandas as pd

## 2. Konfiguracija

In [2]:
if torch.cuda.is_available():
    from google.colab import drive
    drive.mount('/content/drive')
    PROJECT_ROOT = Path("/content/drive/MyDrive/RecSys")
else:
    PROJECT_ROOT = Path.cwd().parent
print('PROJECT_ROOT:', PROJECT_ROOT.resolve())
sys.path.insert(0, str(PROJECT_ROOT))

Mounted at /content/drive
PROJECT_ROOT: /content/drive/MyDrive/RecSys

In [ ]:
SEED = 42
MAX_NEW_TOKENS = 256
JUDGE_MODEL_ID = "Qwen/Qwen3-4B-Instruct-2507"
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = 'cuda'  if torch.cuda.is_available() else 'cpu'
EVAL_DIR = PROJECT_ROOT / 'data' / 'evaluation'
TEST_POOL_PATH = EVAL_DIR / 'llm_test_pool.csv' #Model je prvo pokrenut nad llm_test_pool.csv kako bi se korigovao prompt. 
POOL_PATH = EVAL_DIR / 'judge_pool.csv'
RESULT_PATH = EVAL_DIR / 'qrels.csv'

input_pool = pd.read_csv(POOL_PATH).fillna('')

print('Test pairs:', len(input_pool))
print('Queries per type:')
display(input_pool['query_type'].value_counts().sort_index())

Test pairs: 489
Queries per type:

query_type
broad_or_underspecified           103
multiple_requirements             127
problem_or_negative_constraint    156
single_property                   103
Name: count, dtype: int64

Pool obuhvata različite tipove upita kako bi se proverilo da li llm razume jednostavne, višestruke, negativne i široko formulisane potrebe.

## 3. Definisanje skale relevantnosti i sistemskog prompta


Za ocene se koristi ordinalna skala:
- 0 - nerelevantan: pogrešan proizvod ili funkcija, nema dokaza za centralnu potrebu ili joj dokazi direktno protivreče
- 1 - delimično relevantan: tip proizvoda je približno odgovarajući, ali je centralni ili dodatni zahtev nepodržan, sporan ili direktno kontradiktoran
- 2 - relevantan: centralna potreba je podržana, ali dodatni eksplicitni zahtev nedostaje ili je neizvestan
- 3 - veoma relevantan: svi eksplicitni zahtevi su potvrđeni i ne postoji kontradikcija

In [4]:
SYSTEM_PROMPT = """You are a conservative relevance assessor for a cosmetics product retrieval system.

Judge exactly one query-product pair using only the supplied query and product evidence. Do not use outside knowledge, ratings, popularity, retrieval rank, similarity, or model identity. Do not infer medical or allergy safety.

First identify every explicit query requirement, including product type, function, finish, shade, skin type, coverage, durability, use case, price, brand, and negative constraints.

Use exactly this ordinal scale:
0 = Irrelevant: wrong product or function, no meaningful evidence for the central need, or the central need is clearly contradicted with credible supporting evidence.
1 = Marginally relevant: the product type is approximately suitable, but the central requirement is unsupported, disputed, or contradicted; also use 1 when an otherwise suitable product directly contradicts an explicit additional requirement.
2 = Relevant: the central need is supported, but an explicit additional requirement is missing or uncertain.
3 = Highly relevant: every explicit requirement is affirmatively supported and there is no query-relevant contradiction.

Evidence rules:
- Missing or uncertain evidence does not satisfy a requirement.
- Absence of evidence is not automatically a contradiction.
- Consider both pros and cons before assigning the grade.
- A direct query-relevant statement in cons is evidence and must not be ignored.
- If pros and cons directly conflict about the same explicit requirement, the grade cannot be 3. Normally use 1 because the requirement is disputed.
- Ignore negative evidence unrelated to the explicit query. For example, price complaints do not matter unless price is requested.
- Do not treat implied, typical, or common product properties as confirmed evidence.
- Grade 3 is allowed only when all explicit requirements have supplied affirmative evidence and none has relevant contradictory evidence.
- If any requirement is described as missing, uncertain, partial, unsupported, or contradicted in the justification, do not assign grade 3.
- A contradiction exists only when supplied evidence directly states or clearly demonstrates the opposite of an explicit query requirement.
- Do not infer a contradiction from a loosely related property or side effect.
- Missing, indirect, or uncertain evidence must be described as missing or uncertain, never as contradictory.
- Consider a negative item from cons only when it directly concerns an explicit query requirement or the basic requested product function.

Return exactly one valid JSON object with no markdown or additional text.
The justification must contain at most 60 words and at most two short sentences. Mention the decisive supporting evidence and any query-relevant contradiction.

Required format:
{"relevance": 0, "justification": "Concise evidence-based explanation."}
"""

## 4. Formiranje poruke za sudiju

In [5]:
def build_messages(row) :
    judging = {
        "query": row["query_text"],
        "product": {
            "name": row["product_name"],"brand": row["brand"],"category": row["category"],
            "description": row["description"],
            "pros": row["pros"],"cons": row["cons"],"best_uses": row["best_uses"]}}
    return[
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user","content":"Assess this pair:\n"+json.dumps(judging, ensure_ascii=False)}
    ]

In [6]:
preview_messages = build_messages(input_pool.iloc[0].to_dict())
print('SYSTEM:')
print(preview_messages[0]['content'])
print('USER:')
print(preview_messages[1]['content'])

SYSTEM:
You are a conservative relevance assessor for a cosmetics product retrieval system.

Judge exactly one query-product pair using only the supplied query and product evidence. Do not use outside knowledge, ratings, popularity, retrieval rank, similarity, or model identity. Do not infer medical or allergy safety.

First identify every explicit query requirement, including product type, function, finish, shade, skin type, coverage, durability, use case, price, brand, and negative constraints.

Use exactly this ordinal scale:
0 = Irrelevant: wrong product or function, no meaningful evidence for the central need, or the central need is clearly contradicted with credible supporting evidence.
1 = Marginally relevant: the product type is approximately suitable, but the central requirement is unsupported, disputed, or contradicted; also use 1 when an otherwise suitable product directly contradicts an explicit additional requirement.
2 = Relevant: the central need is supported, but an explicit additional requirement is missing or uncertain.
3 = Highly relevant: every explicit requirement is affirmatively supported and there is no query-relevant contradiction.

Evidence rules:
- Missing or uncertain evidence does not satisfy a requirement.
- Absence of evidence is not automatically a contradiction.
- Consider both pros and cons before assigning the grade.
- A direct query-relevant statement in cons is evidence and must not be ignored.
- If pros and cons directly conflict about the same explicit requirement, the grade cannot be 3. Normally use 1 because the requirement is disputed.
- Ignore negative evidence unrelated to the explicit query. For example, price complaints do not matter unless price is requested.
- Do not treat implied, typical, or common product properties as confirmed evidence.
- Grade 3 is allowed only when all explicit requirements have supplied affirmative evidence and none has relevant contradictory evidence.
- If any requirement is described as missing, uncertain, partial, unsupported, or contradicted in the justification, do not assign grade 3.
- A contradiction exists only when supplied evidence directly states or clearly demonstrates the opposite of an explicit query requirement.
- Do not infer a contradiction from a loosely related property or side effect.
- Missing, indirect, or uncertain evidence must be described as missing or uncertain, never as contradictory.
- Consider a negative item from cons only when it directly concerns an explicit query requirement or the basic requested product function.

Return exactly one valid JSON object with no markdown or additional text.
The justification must contain at most 60 words and at most two short sentences. Mention the decisive supporting evidence and any query-relevant contradiction.

Required format:
{"relevance": 0, "justification": "Concise evidence-based explanation."}

USER:
Assess this pair:
{"query": "Tinted moisturizer with a natural finish that lasts through a day of hiking", "product": {"name": "Mini Tinted Moisturizer Natural Skin Perfector Broad Spectrum SPF 30", "brand": "Laura Mercier", "category": "Tinted Moisturizer", "description": "The Mini Tinted Moisturizer Natural Skin Perfector Broad Spectrum SPF 30 is Laura Mercier's skin-perfecting secret to a flawless, dewy, no-makeup-makeup look. This multitasking blend of skincare and makeup blurs imperfections, with a sheer hint of coverage. Details Benefits Key Ingredients Perfect your skin with a sheer hint of coverage for an effortless no-makeup makeup dewy finish The perfect blend of skincare & makeup improves your skin over time with a hydrating complex made up of Macadamia & Kukui seed oils that helps increase the skin's moisture levels long-term for 24 hours of hydration, while reducing the signs of visibly dry skin Lightweight formula, infused with Tamarind seed extract, helps skin retain moisture to prevent water evaporation, for long lasting hydration Broad Spectrum SPF 30 UVB/UVA sunscreen plus a power-blend of antioxidant vitamins C & E help protect skin from the damaging effects of the environment Macadamia & Kukui seed oils to support healthy skin function Tamarind seed extract to lock in moisture & give enhanced antioxidant protection Silica treated pigments helps create a soft focus effect for a naturally dewy finish Glycerin to soften fine lines, revitalizing hydration Vitamin complex of C & E to protect the skin from environmental agressors Broad spectrum SPF 30 UVA/UVB sunscreen for ideal protection from the sun's harmful, skin-damaging rays How To Use Place a small amount on the back of your hand and apply to face with a makeup sponge or with clean fingertips. Focus on one area at a time and blend well. For best results, use after your preferred Laura Mercier Foundation Primer (sold separately).", "pros": "flattering/good shade match, natural-looking finish, glowy/radiant finish, good/buildable coverage, smooth/creamy texture, blends easily, easy to apply/use", "cons": "difficult to blend, heavy/thick feel, too shiny/glittery", "best_uses": "travel/on-the-go touch-ups, alone instead of foundation, covering blemishes/dark spots, mature skin"}}

### Rezultat pregleda prompta

Prikazani sadržaj predstavlja tačan ulaz koji će model dobiti za svaki query–product par. Menjaju se samo konkretan upit i podaci proizvoda, dok sistemska pravila ostaju ista.

## 5. Učitavanje Qwen judge modela

In [7]:
MODEL_REVISION = model_info(JUDGE_MODEL_ID).sha

tokenizer = AutoTokenizer.from_pretrained(JUDGE_MODEL_ID, revision=MODEL_REVISION)
judge_model = AutoModelForCausalLM.from_pretrained(JUDGE_MODEL_ID, revision=MODEL_REVISION,torch_dtype=torch.float16, device_map='auto', low_cpu_mem_usage=True,)
judge_model.eval()

config.json:   0%|          | 0.00/727 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/9.38k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/32.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/238 [00:00<?, ?B/s]

Qwen3ForCausalLM(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 2560)
    (layers): ModuleList(
      (0-35): 36 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((2560,), eps=1e-06)
    (rotary_emb): Qwen3RotaryEmbedding()
  )
  (lm_head): Linear(in_features=2560, out_features=151936, bias=False)
)

## 6. Generisanje ocena relevantnosti

Sudija mora da vrati tačno jedan JSON objekat sa dve vrednosti
{
  "relevance": 0,
  "justification": "Concise evidence-based explanation."
}
Nevalidan format se beleži kao greška

In [ ]:
def parse_judgment(response):
    try:
        payload = json.loads(response.strip())
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid format detected : {e}")
    if not isinstance(payload, dict):
        raise ValueError("Judge response must be a JSON object.")

    relevance = payload.get("relevance")
    justification = payload.get("justification")
    if type(relevance) is not int or relevance not in {0, 1, 2, 3}:
        raise ValueError("Relevance must be an integer from 0 to 3.")
    if not isinstance(justification, str):
        raise ValueError("Justification must be a string.")
    justification = re.sub(r"\s+"," ",justification,).strip()
    if len(justification.split()) > 60:
        raise ValueError("Justification must contain at most 60 words")
    if not justification or len(justification) > 600:
        raise ValueError("Justification must contain 1 to 600 characters.")

    return relevance, justification

In [ ]:
def judge_pair(row):
    messages = build_messages(row)
    encoded = tokenizer.apply_chat_template(messages,add_generation_prompt=True, tokenize=True,return_dict=True,return_tensors="pt")
    encoded["input_ids"] = encoded["input_ids"].to(judge_model.device)
    encoded["attention_mask"] = encoded["attention_mask"].to(judge_model.device)
    input_length = encoded["input_ids"].shape[1]

    with torch.inference_mode():
        generated = judge_model.generate(**encoded,do_sample=False,max_new_tokens=MAX_NEW_TOKENS,pad_token_id=tokenizer.eos_token_id)

    raw_response = tokenizer.decode(generated[0, input_length:],skip_special_tokens=True).strip()

    result = {"query_id": row["query_id"],"logical_product_id": row["logical_product_id"],"query_text": row["query_text"],
            "query_type": row["query_type"],"product_name": row["product_name"],"raw_response": raw_response}

    try:
        parsed = parse_judgment(raw_response)

        result["relevance"] = parsed[0]
        result["justification"] = parsed[1]
        result["parse_status"] = "ok"

    except ValueError as error:
        result["relevance"] = pd.NA
        result["justification"] = str(error)
        result["parse_status"] = "error"

    return result

In [ ]:
results = pd.DataFrame()
completed = set()

for row in input_pool.to_dict(orient="records"):
    key = (str(row["query_id"]),str(row["logical_product_id"]))
    if key in completed:
        continue
    result = judge_pair(row)
    results = pd.concat([results,pd.DataFrame([result])],ignore_index=True)
    completed.add(key)
    print(f"{len(completed)}/{len(input_pool)} | status={result['parse_status']} | relevance={result['relevance']}")

results.to_csv(RESULT_PATH, index=False)

1/489 | status=ok | relevance=3
2/489 | status=ok | relevance=3
3/489 | status=ok | relevance=2
4/489 | status=ok | relevance=1
5/489 | status=ok | relevance=1
6/489 | status=ok | relevance=3
7/489 | status=ok | relevance=3
8/489 | status=ok | relevance=3
9/489 | status=ok | relevance=3
10/489 | status=ok | relevance=2
11/489 | status=ok | relevance=3
12/489 | status=ok | relevance=1
13/489 | status=ok | relevance=3
14/489 | status=ok | relevance=3
15/489 | status=ok | relevance=1
16/489 | status=ok | relevance=3
17/489 | status=ok | relevance=1
18/489 | status=ok | relevance=3
19/489 | status=ok | relevance=1
20/489 | status=ok | relevance=3
21/489 | status=ok | relevance=3
22/489 | status=ok | relevance=2
23/489 | status=ok | relevance=3
24/489 | status=ok | relevance=2
25/489 | status=ok | relevance=2
26/489 | status=ok | relevance=3
27/489 | status=ok | relevance=1
28/489 | status=ok | relevance=3
29/489 | status=ok | relevance=1
30/489 | status=ok | relevance=2
31/489 | status=ok | relevance=1
32/489 | status=ok | relevance=2
33/489 | status=ok | relevance=2
34/489 | status=ok | relevance=1
35/489 | status=ok | relevance=1
36/489 | status=ok | relevance=3
37/489 | status=ok | relevance=2
38/489 | status=ok | relevance=3
39/489 | status=ok | relevance=2
40/489 | status=ok | relevance=1
41/489 | status=ok | relevance=2
42/489 | status=ok | relevance=3
43/489 | status=ok | relevance=3
44/489 | status=ok | relevance=1
45/489 | status=ok | relevance=2
46/489 | status=ok | relevance=1
47/489 | status=ok | relevance=1
48/489 | status=ok | relevance=1
49/489 | status=ok | relevance=1
50/489 | status=ok | relevance=3
51/489 | status=ok | relevance=3
52/489 | status=ok | relevance=3
53/489 | status=ok | relevance=2
54/489 | status=ok | relevance=3
55/489 | status=ok | relevance=1
56/489 | status=ok | relevance=2
57/489 | status=ok | relevance=3
58/489 | status=ok | relevance=1
59/489 | status=ok | relevance=1
60/489 | status=ok | relevance=1
61/489 | status=ok | relevance=3
62/489 | status=ok | relevance=3
63/489 | status=ok | relevance=3
64/489 | status=ok | relevance=1
65/489 | status=ok | relevance=3
66/489 | status=ok | relevance=2
67/489 | status=ok | relevance=3
68/489 | status=ok | relevance=2
69/489 | status=ok | relevance=2
70/489 | status=ok | relevance=3
71/489 | status=ok | relevance=3
72/489 | status=ok | relevance=1
73/489 | status=ok | relevance=1
74/489 | status=ok | relevance=2
75/489 | status=ok | relevance=1
76/489 | status=ok | relevance=3
77/489 | status=ok | relevance=3
78/489 | status=ok | relevance=1
79/489 | status=ok | relevance=2
80/489 | status=ok | relevance=3
81/489 | status=ok | relevance=3
82/489 | status=ok | relevance=1
83/489 | status=ok | relevance=1
84/489 | status=ok | relevance=2
85/489 | status=ok | relevance=0
86/489 | status=ok | relevance=3
87/489 | status=ok | relevance=3
88/489 | status=ok | relevance=3
89/489 | status=ok | relevance=2
90/489 | status=ok | relevance=3
91/489 | status=ok | relevance=2
92/489 | status=ok | relevance=3
93/489 | status=ok | relevance=1
94/489 | status=ok | relevance=1
95/489 | status=ok | relevance=2
96/489 | status=ok | relevance=1
97/489 | status=ok | relevance=0
98/489 | status=ok | relevance=1
99/489 | status=ok | relevance=1
100/489 | status=ok | relevance=3
101/489 | status=ok | relevance=3
102/489 | status=ok | relevance=3
103/489 | status=ok | relevance=2
104/489 | status=ok | relevance=1
105/489 | status=ok | relevance=3
106/489 | status=ok | relevance=3
107/489 | status=ok | relevance=3
108/489 | status=ok | relevance=2
109/489 | status=ok | relevance=0
110/489 | status=ok | relevance=3
111/489 | status=ok | relevance=2
112/489 | status=ok | relevance=3
113/489 | status=ok | relevance=2
114/489 | status=ok | relevance=2
115/489 | status=ok | relevance=1
116/489 | status=ok | relevance=2
117/489 | status=ok | relevance=1
118/489 | status=ok | relevance=3
119/489 | status=ok | relevance=1
120/489 | status=ok | relevance=1
121/489 | status=ok | relevance=3
122/489 | status=ok | relevance=2
123/489 | status=ok | relevance=1
124/489 | status=ok | relevance=3
125/489 | status=ok | relevance=3
126/489 | status=ok | relevance=0
127/489 | status=ok | relevance=1
128/489 | status=ok | relevance=3
129/489 | status=ok | relevance=1
130/489 | status=ok | relevance=1
131/489 | status=ok | relevance=2
132/489 | status=ok | relevance=3
133/489 | status=ok | relevance=1
134/489 | status=ok | relevance=1
135/489 | status=ok | relevance=3
136/489 | status=ok | relevance=3
137/489 | status=ok | relevance=1
138/489 | status=ok | relevance=3
139/489 | status=ok | relevance=1
140/489 | status=ok | relevance=2
141/489 | status=ok | relevance=2
142/489 | status=ok | relevance=3
143/489 | status=ok | relevance=3
144/489 | status=ok | relevance=2
145/489 | status=ok | relevance=3
146/489 | status=ok | relevance=3
147/489 | status=ok | relevance=1
148/489 | status=ok | relevance=2
149/489 | status=ok | relevance=3
150/489 | status=ok | relevance=3
151/489 | status=ok | relevance=1
152/489 | status=ok | relevance=2
153/489 | status=ok | relevance=3
154/489 | status=ok | relevance=3
155/489 | status=ok | relevance=2
156/489 | status=ok | relevance=2
157/489 | status=ok | relevance=2
158/489 | status=ok | relevance=3
159/489 | status=ok | relevance=0
160/489 | status=ok | relevance=1
161/489 | status=ok | relevance=1
162/489 | status=ok | relevance=3
163/489 | status=ok | relevance=3
164/489 | status=ok | relevance=3
165/489 | status=ok | relevance=3
166/489 | status=ok | relevance=1
167/489 | status=ok | relevance=3
168/489 | status=ok | relevance=3
169/489 | status=ok | relevance=2
170/489 | status=ok | relevance=0
171/489 | status=ok | relevance=3
172/489 | status=ok | relevance=1
173/489 | status=ok | relevance=3
174/489 | status=ok | relevance=3
175/489 | status=ok | relevance=3
176/489 | status=ok | relevance=1
177/489 | status=ok | relevance=2
178/489 | status=ok | relevance=1
179/489 | status=ok | relevance=2
180/489 | status=ok | relevance=1
181/489 | status=ok | relevance=2
182/489 | status=ok | relevance=2
183/489 | status=ok | relevance=3
184/489 | status=ok | relevance=2
185/489 | status=ok | relevance=1
186/489 | status=ok | relevance=1
187/489 | status=ok | relevance=1
188/489 | status=ok | relevance=3
189/489 | status=ok | relevance=1
190/489 | status=ok | relevance=3
191/489 | status=ok | relevance=3
192/489 | status=ok | relevance=3
193/489 | status=ok | relevance=3
194/489 | status=ok | relevance=2
195/489 | status=ok | relevance=3
196/489 | status=ok | relevance=3
197/489 | status=ok | relevance=3
198/489 | status=ok | relevance=3
199/489 | status=ok | relevance=1
200/489 | status=ok | relevance=0
201/489 | status=ok | relevance=3
202/489 | status=ok | relevance=1
203/489 | status=ok | relevance=1
204/489 | status=ok | relevance=1
205/489 | status=ok | relevance=3
206/489 | status=ok | relevance=2
207/489 | status=ok | relevance=3
208/489 | status=ok | relevance=3
209/489 | status=ok | relevance=3
210/489 | status=ok | relevance=3
211/489 | status=ok | relevance=3
212/489 | status=ok | relevance=1
213/489 | status=ok | relevance=3
214/489 | status=ok | relevance=1
215/489 | status=ok | relevance=3
216/489 | status=ok | relevance=0
217/489 | status=ok | relevance=1
218/489 | status=ok | relevance=1
219/489 | status=ok | relevance=3
220/489 | status=ok | relevance=1
221/489 | status=ok | relevance=2
222/489 | status=ok | relevance=3
223/489 | status=ok | relevance=2
224/489 | status=ok | relevance=3
225/489 | status=ok | relevance=1
226/489 | status=ok | relevance=0
227/489 | status=ok | relevance=1
228/489 | status=ok | relevance=3
229/489 | status=ok | relevance=3
230/489 | status=ok | relevance=3
231/489 | status=ok | relevance=0
232/489 | status=ok | relevance=3
233/489 | status=ok | relevance=2
234/489 | status=ok | relevance=2
235/489 | status=ok | relevance=2
236/489 | status=ok | relevance=3
237/489 | status=ok | relevance=1
238/489 | status=ok | relevance=3
239/489 | status=ok | relevance=1
240/489 | status=ok | relevance=1
241/489 | status=ok | relevance=3
242/489 | status=ok | relevance=1
243/489 | status=ok | relevance=2
244/489 | status=ok | relevance=0
245/489 | status=ok | relevance=2
246/489 | status=ok | relevance=0
247/489 | status=ok | relevance=2
248/489 | status=ok | relevance=1
249/489 | status=ok | relevance=2
250/489 | status=ok | relevance=0
251/489 | status=ok | relevance=1
252/489 | status=ok | relevance=2
253/489 | status=ok | relevance=3
254/489 | status=ok | relevance=3
255/489 | status=ok | relevance=2
256/489 | status=ok | relevance=3
257/489 | status=ok | relevance=2
258/489 | status=ok | relevance=3
259/489 | status=ok | relevance=1
260/489 | status=ok | relevance=3
261/489 | status=ok | relevance=2
262/489 | status=ok | relevance=3
263/489 | status=ok | relevance=3
264/489 | status=ok | relevance=2
265/489 | status=ok | relevance=1
266/489 | status=ok | relevance=2
267/489 | status=ok | relevance=1
268/489 | status=ok | relevance=3
269/489 | status=ok | relevance=3
270/489 | status=ok | relevance=2
271/489 | status=ok | relevance=3
272/489 | status=ok | relevance=3
273/489 | status=ok | relevance=1
274/489 | status=ok | relevance=3
275/489 | status=ok | relevance=2
276/489 | status=ok | relevance=3
277/489 | status=ok | relevance=3
278/489 | status=ok | relevance=1
279/489 | status=ok | relevance=3
280/489 | status=ok | relevance=2
281/489 | status=ok | relevance=1
282/489 | status=ok | relevance=3
283/489 | status=ok | relevance=1
284/489 | status=ok | relevance=2
285/489 | status=ok | relevance=3
286/489 | status=ok | relevance=3
287/489 | status=ok | relevance=1
288/489 | status=ok | relevance=2
289/489 | status=ok | relevance=1
290/489 | status=ok | relevance=1
291/489 | status=ok | relevance=2
292/489 | status=ok | relevance=3
293/489 | status=ok | relevance=1
294/489 | status=ok | relevance=0
295/489 | status=ok | relevance=1
296/489 | status=ok | relevance=3
297/489 | status=ok | relevance=3
298/489 | status=ok | relevance=3
299/489 | status=ok | relevance=2
300/489 | status=ok | relevance=3
301/489 | status=ok | relevance=0
302/489 | status=ok | relevance=3
303/489 | status=ok | relevance=2
304/489 | status=ok | relevance=1
305/489 | status=ok | relevance=2
306/489 | status=ok | relevance=3
307/489 | status=ok | relevance=3
308/489 | status=ok | relevance=3
309/489 | status=ok | relevance=0
310/489 | status=ok | relevance=1
311/489 | status=ok | relevance=1
312/489 | status=ok | relevance=3
313/489 | status=ok | relevance=3
314/489 | status=ok | relevance=3
315/489 | status=ok | relevance=1
316/489 | status=ok | relevance=3
317/489 | status=ok | relevance=2
318/489 | status=ok | relevance=3
319/489 | status=ok | relevance=1
320/489 | status=ok | relevance=2
321/489 | status=ok | relevance=1
322/489 | status=ok | relevance=3
323/489 | status=ok | relevance=1
324/489 | status=ok | relevance=2
325/489 | status=ok | relevance=2
326/489 | status=ok | relevance=3
327/489 | status=ok | relevance=2
328/489 | status=ok | relevance=3
329/489 | status=ok | relevance=3
330/489 | status=ok | relevance=3
331/489 | status=ok | relevance=3
332/489 | status=ok | relevance=3
333/489 | status=ok | relevance=2
334/489 | status=ok | relevance=2
335/489 | status=ok | relevance=1
336/489 | status=ok | relevance=2
337/489 | status=ok | relevance=2
338/489 | status=ok | relevance=3
339/489 | status=ok | relevance=3
340/489 | status=ok | relevance=1
341/489 | status=ok | relevance=3
342/489 | status=ok | relevance=3
343/489 | status=ok | relevance=2
344/489 | status=ok | relevance=3
345/489 | status=ok | relevance=2
346/489 | status=ok | relevance=1
347/489 | status=ok | relevance=3
348/489 | status=ok | relevance=3
349/489 | status=ok | relevance=3
350/489 | status=ok | relevance=3
351/489 | status=ok | relevance=3
352/489 | status=ok | relevance=3
353/489 | status=ok | relevance=3
354/489 | status=ok | relevance=3
355/489 | status=ok | relevance=1
356/489 | status=ok | relevance=3
357/489 | status=ok | relevance=1
358/489 | status=ok | relevance=1
359/489 | status=ok | relevance=1
360/489 | status=ok | relevance=3
361/489 | status=ok | relevance=1
362/489 | status=ok | relevance=3
363/489 | status=ok | relevance=1
364/489 | status=ok | relevance=1
365/489 | status=ok | relevance=3
366/489 | status=ok | relevance=3
367/489 | status=ok | relevance=3
368/489 | status=ok | relevance=3
369/489 | status=ok | relevance=3
370/489 | status=ok | relevance=2
371/489 | status=ok | relevance=2
372/489 | status=ok | relevance=3
373/489 | status=ok | relevance=3
374/489 | status=ok | relevance=2
375/489 | status=ok | relevance=1
376/489 | status=ok | relevance=2
377/489 | status=ok | relevance=1
378/489 | status=ok | relevance=2
379/489 | status=ok | relevance=1
380/489 | status=ok | relevance=3
381/489 | status=ok | relevance=3
382/489 | status=ok | relevance=1
383/489 | status=ok | relevance=1
384/489 | status=ok | relevance=1
385/489 | status=ok | relevance=1
386/489 | status=ok | relevance=2
387/489 | status=ok | relevance=3
388/489 | status=ok | relevance=1
389/489 | status=ok | relevance=3
390/489 | status=ok | relevance=3
391/489 | status=ok | relevance=3
392/489 | status=ok | relevance=3
393/489 | status=ok | relevance=3
394/489 | status=ok | relevance=3
395/489 | status=ok | relevance=2
396/489 | status=ok | relevance=1
397/489 | status=ok | relevance=2
398/489 | status=ok | relevance=1
399/489 | status=ok | relevance=1
400/489 | status=ok | relevance=3
401/489 | status=ok | relevance=3
402/489 | status=ok | relevance=2
403/489 | status=ok | relevance=1
404/489 | status=ok | relevance=2
405/489 | status=ok | relevance=3
406/489 | status=ok | relevance=1
407/489 | status=ok | relevance=3
408/489 | status=ok | relevance=1
409/489 | status=ok | relevance=3
410/489 | status=ok | relevance=3
411/489 | status=ok | relevance=2
412/489 | status=ok | relevance=1
413/489 | status=ok | relevance=3
414/489 | status=ok | relevance=2
415/489 | status=ok | relevance=2
416/489 | status=ok | relevance=1
417/489 | status=ok | relevance=3
418/489 | status=ok | relevance=3
419/489 | status=ok | relevance=3
420/489 | status=ok | relevance=1
421/489 | status=ok | relevance=3
422/489 | status=ok | relevance=2
423/489 | status=ok | relevance=2
424/489 | status=ok | relevance=3
425/489 | status=ok | relevance=1
426/489 | status=ok | relevance=3
427/489 | status=ok | relevance=2
428/489 | status=ok | relevance=1
429/489 | status=ok | relevance=3
430/489 | status=ok | relevance=3
431/489 | status=ok | relevance=1
432/489 | status=ok | relevance=2
433/489 | status=ok | relevance=1
434/489 | status=ok | relevance=3
435/489 | status=ok | relevance=3
436/489 | status=ok | relevance=1
437/489 | status=ok | relevance=3
438/489 | status=ok | relevance=3
439/489 | status=ok | relevance=3
440/489 | status=ok | relevance=1
441/489 | status=ok | relevance=3
442/489 | status=ok | relevance=0
443/489 | status=ok | relevance=1
444/489 | status=ok | relevance=1
445/489 | status=ok | relevance=1
446/489 | status=ok | relevance=3
447/489 | status=ok | relevance=3
448/489 | status=ok | relevance=2
449/489 | status=ok | relevance=3
450/489 | status=ok | relevance=1
451/489 | status=ok | relevance=2
452/489 | status=ok | relevance=1
453/489 | status=ok | relevance=3
454/489 | status=ok | relevance=1
455/489 | status=ok | relevance=3
456/489 | status=ok | relevance=3
457/489 | status=ok | relevance=2
458/489 | status=ok | relevance=3
459/489 | status=ok | relevance=2
460/489 | status=ok | relevance=3
461/489 | status=ok | relevance=1
462/489 | status=ok | relevance=1
463/489 | status=ok | relevance=3
464/489 | status=ok | relevance=1
465/489 | status=ok | relevance=3
466/489 | status=ok | relevance=3
467/489 | status=ok | relevance=3
468/489 | status=ok | relevance=3
469/489 | status=ok | relevance=1
470/489 | status=ok | relevance=2
471/489 | status=ok | relevance=1
472/489 | status=ok | relevance=2
473/489 | status=ok | relevance=3
474/489 | status=ok | relevance=1
475/489 | status=ok | relevance=3
476/489 | status=ok | relevance=3
477/489 | status=ok | relevance=3
478/489 | status=ok | relevance=3
479/489 | status=ok | relevance=2
480/489 | status=ok | relevance=2
481/489 | status=ok | relevance=3
482/489 | status=ok | relevance=3
483/489 | status=ok | relevance=3
484/489 | status=ok | relevance=2
485/489 | status=ok | relevance=3
486/489 | status=ok | relevance=2
487/489 | status=ok | relevance=2
488/489 | status=ok | relevance=1
489/489 | status=ok | relevance=1

## 7.Pregled ocena

Proverava se da:
- svaki odgovor ima parse_status="ok"
- sve relevance ocene pripadaju skupu 0–3
- relevance kolona može da se pretvori u celobrojni tip bez greške

Kod manjeg test podskupa radi modifikacije prompta je ručno provereno da li:
- model dosledno koristi skalu 0–3
- koristi samo prosleđene dokaze
- izbegava halucinacije
- poštuje eksplicitne negativne zahteve
- relevantne kontradikcije iz cons utiču na ocenu
- obrazloženje odgovara dodeljenoj oceni

In [11]:
results = pd.read_csv(RESULT_PATH, dtype={'query_id': 'string', 'logical_product_id': 'string'})
assert results['parse_status'].eq('ok').all(), ('At least one output is invalid. Inspect raw_response')
assert results['relevance'].between(0, 3).all()
results['relevance'] = pd.to_numeric(results['relevance'], errors='raise').astype(int)

print('Relevance distribution:')
display(results['relevance'].value_counts().sort_index())
print('Grades by query type:')
display(pd.crosstab(results['query_type'], results['relevance']))

Relevance distribution:

relevance
0     17
1    142
2    110
3    220
Name: count, dtype: int64

Grades by query type:

relevance                       0   1   2   3
query_type
broad_or_underspecified         4   8  31  60
multiple_requirements           3  38  31  55
problem_or_negative_constraint  9  84  27  36
single_property                 1  12  21  69